### ISSUE TITLE
[demo-app]: Simple Encryption throws error when app is not connected

### ISSUE THREAD

**Issue by Hacklor** [philips-software/cogito#71]
When I encrypt a message, but don't have the app open, it throws the following exception.

Steps to reproduce:
Make sure you do not have the app connected.

1: Go to Simple Encryption
2: Fill in a message
3: Click to "Encrypt"

<img width="1042" alt="screenshot 2019-02-14 at 11 15 47" src="https://user-images.githubusercontent.com/3730478/52780244-0b7d8780-304a-11e9-92c1-0dd88768be5e.png">

**Comment by markspanbroek** [comment]
This is probably caused by the Telepath Queue being full. The demo app allows you to click on 'encrypt', even when it has already been clicked. Each click results in an item being sent over the queue, and when the queue reaches a size of 10, it will return an error.

This should probably be tackled by ensuring that the button is disabled when it is clicked. Additionally, it would be nice to prompt the user to open the app when no response is received.

**Comment by Hacklor** [comment]
Solved in #110 , closing
