### ISSUE TITLE
[demo-app]: Simple Encryption throws error when missing encrypted symmetric key

### ISSUE THREAD

**Issue by Hacklor** [philips-software/cogito#88]
The demo-app throws an exception when the simple encryption contains a non encrypted message and the "Decrypt" button is pressed.

<img width="1030" alt="screenshot 2019-02-26 at 11 08 34" src="https://user-images.githubusercontent.com/3730478/53404953-06f48f80-39b7-11e9-96f0-14c31b8f1691.png">

**Comment by marcinczenko** [comment]
The whole encryption demo page needs to be redesigned to make it more aligned with the first two demos (identity and contracts). There it will be possible to handle these errors (which by all means are intended) and if this is needed communicate them to the user. The encryption demo is not consistent in the sense that it allows you to press buttons without even having a telepath channel establish. The other two demos (identity and contracts) prevent that from happening and they display the QR code when this is detected. The general principle for each demo is that the user should be able to select any demo as the first one to try and things should not brake. Currently, this is observed only for identity and smart-contracts demos and so before starting the encryption, the user is assumed to already have telepath channel created by the means of identity or smart-contracts demos.

I suspect that the same comment applies to the issues: #86, #87, and #71.

In fixing this issue and some other issues I would recommend having in mind that demo-app is intended for software developers to learn how to connect various cogito-components together *in code*. The UI around the demos has to be reliable, so that it does not crash (like it is now for simple encryption), but taken the intended audience some small imperfections are forgivable ;).

**Comment by Hacklor** [comment]
The page now shows an error message

Solved in #110 , closing
